// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC08nYj0Uoii1eXvY8HpFjl_KqOAWJgdLQ',
    appId: '1:815307938879:web:6878002a574eecb1bcac8a',
    messagingSenderId: '815307938879',
    projectId: 'evently-b8807',
    authDomain: 'evently-b8807.firebaseapp.com',
    storageBucket: 'evently-b8807.firebasestorage.app',
    measurementId: 'G-MJN4PP7B8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdZkDMxL9NeeVPhk130vdVkRVq4uQfsvk',
    appId: '1:815307938879:android:6df5180b05a8ce6bbcac8a',
    messagingSenderId: '815307938879',
    projectId: 'evently-b8807',
    storageBucket: 'evently-b8807.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP0e1SlyRXw5he1vcxIpkONabrPB0JqLA',
    appId: '1:815307938879:ios:9fb950254875c5cdbcac8a',
    messagingSenderId: '815307938879',
    projectId: 'evently-b8807',
    storageBucket: 'evently-b8807.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );
}
